#!/bin/sh

mkdir /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs none /tmp
mdev -s
echo -e "Boot took $(cut -d' ' -f1 /proc/uptime) seconds"

insmod /test1.ko
chmod 666 /dev/test1
chmod 600 /flag
poweroff -d 120 -f &
setsid /bin/cttyhack setuidgid pwn /bin/sh 

poweroff -d 0  -f
